### ISSUE TITLE
Git problem when using locally deployed overleaf

### ISSUE THREAD

**Issue by Jinbo-He** [iamhyc/Overleaf-Workshop#207]
### Describe the bug
> A clear and concise description of what the bug is.
I am using a locally deployed Overleaf instance and attempting to integrate it with Git through VS Code. However, when initializing a Git repository in VS Code, a path error occurs, preventing the repository from being recognized correctly by Overleaf. I am wondering if this could be solved?

### Expected behavior
> A clear and concise description of what you expected to happen.
I expected to seamlessly integrate Git with VS Code and Overleaf, allowing for smooth repository initialization and interaction.

### How To Reproduce
> Detailed steps to reproduce the behavior.
	1.	Use a locally deployed Overleaf instance.
	2.	Open VS Code and initialize a Git repository.
	3.	Observe the path error during the initialization process.
<img width="1968" alt="image" src="https://github.com/user-attachments/assets/a4aa05d9-adf7-4d35-8f4a-05b7eacfcde1">

### Environment
 - **Overleaf Workshop Extension version**: v0.14.1
 - **VS Code version**: 1.95.3
 - **Overleaf Edition**: Community 

### [Optional] Developer Logs
> If applicable, please paste the logs inside the details section below.
> Please find the logs via: Title bar **"Help"** > **"Toggle Developer Tools"** > **"Console"**.

<details>
  ...
</details>

**Comment by iamhyc** [comment]
Sorry for the late response. I will check it later today.

**Comment by iamhyc** [comment]
> I am using a locally deployed Overleaf instance

I think the problem is not related to "locally deployed" instance, but you are opening the Overleaf workspace in vscode as [virtual workspace](https://code.visualstudio.com/api/extension-guides/virtual-workspaces).

If you need to integrate it with local git, for now, you need to "open the project locally". Please refer to the guidance here: https://github.com/iamhyc/Overleaf-Workshop/blob/master/docs/wiki.md#open-project-locally

Though the "open project locally" feature is not stable now (you can check the other issues in this repo), it is safe for you local instance.
