### ISSUE TITLE
How to do On-the-fly Compiling?

### ISSUE THREAD

**Issue by blacktanktop** [iamhyc/Overleaf-Workshop#50]
Thanks for creating a great tool!

I know that I can access the Overleaf server and write and chat, but I don't know the details of the commands (shortcuts) to compile and view the PDF on the VSCode, so please help!

I also know that it is possible to copy the PDF locally, but I would like to know how to do that.

**Comment by blacktanktop** [comment]
I solved myself about the pdf preview.
I think .output.pdf automatically reflects changes when you change the tex.

I'm still not sure how to copy it locally at the moment, so I want to know

**Comment by iamhyc** [comment]
Hi @blacktanktop , sorry for the late response, I will answer your question one by one:

> I know that I can access the Overleaf server and write and chat, but I don't know the details of the commands (shortcuts)

![](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/b796c327-efb8-42bd-a2e7-a41d1bb14c38)

You can find the commands/shortcuts details in command palette. As for the compile part, we use the same keybindings as the well-known LaTex-Workshop, `ctrl+alt+b` for compile and `ctrl+alt+v` for view.

> I also know that it is possible to copy the PDF locally

![](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/cd992828-9156-420d-ae5c-6ea149c2eb47)

If you open the project via "Open Project in Current Window"/"Open Project in New Window", you are actually have a [virtual workspace](https://code.visualstudio.com/api/extension-guides/virtual-workspaces) opened. You can simply right-click on the file and click "Download..." to save it locally on your disk.

Otherwise, if you open the project via "Open Project Locally ...", then the project is always keep in sync locally on your disk and you can apply common copy/move actions. For more details, please refer to the "Open Project Locally GIF", https://github.com/iamhyc/Overleaf-Workshop#features 

> I think .output.pdf automatically reflects changes when you change the tex.

You are right. All the compile output files generated on overleaf server are stored in the `.output` folder.

**Comment by blacktanktop** [comment]
Thanks for the very detail explanation!
I just tried a lot of things, shortcuts, copy to local, etc.
I think it's a great tool and I look forward to more development!
